development:
  sessions:
    default:
      database: open_farm_development
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
  options:

test:
  sessions:
    default:
      database: open_farm_test
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
